### signup user

POST http://localhost:5174/signup
Content-Type: application/json

{
    "email": "tcl@qq.com",
    "dept_id": 1,
    "roles": [1, 3],
    "username": "Alice Shi",
    "password": "123456",
    "status": "active",
    "phone": "139",
    "created_time": "2023-01-01T00:00:00Z",
    "updated_time": "2023-01-01T00:00:00Z",
    "avatar": "default"
}


### signin user

# @name signin
POST http://localhost:5174/api/v1/signin
Content-Type: application/json

{
    "email": "elixy@qq.com",
    "password": "123456"
}

@token = {{ signin.response.body.token }}

### get user

GET http://localhost:5174/api/v1/user/1
Content-Type: application/json
Authorization: Bearer {{ token }}


### get users

GET http://localhost:5174/api/v1/user
Content-Type: application/json
Authorization: Bearer {{ token }}

{

}


### get users by condition

GET http://localhost:5174/api/v1/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "test"
}


POST http://localhost:5174/api/v1/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "deptId": 1,
    "username": "Yao Y",
    "password": "123456",
    "email": "yaoy@gmail.com",
    "phone": "123456789",
    "status": "active",
    "avatar": "default",
    "roles": [
        1, 2, 3
    ]
}

### update user

POST http://localhost:5174/api/v1/user/13
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "deptId": 1,
    "username": "Yao Y",
    "email": "elixy@qq.com",
    "phone": "123456789",
    "status": "active",
    "avatar": "default",
    "roles": [
        1, 2, 3
    ]
}